name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Validate Kubernetes YAML
      run: |
        kubectl kustomize k8s-specifications/

    - name: Build Vote Docker Image
      run: |
        docker build -t voting-app ./vote

    - name: Success Message
      run: echo "CI Pipeline completed successfully!"